In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
data = pd.read_csv('diabetes.csv')

df = data.copy()

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [8]:
df.Pregnancies.unique()

array([ 6,  1,  8,  0,  5,  3, 10,  2,  4,  7,  9, 11, 13, 15, 17, 12, 14])

In [7]:
df.groupby(['Pregnancies'])['Outcome'].mean()

Pregnancies
0     0.342342
1     0.214815
2     0.184466
3     0.360000
4     0.338235
5     0.368421
6     0.320000
7     0.555556
8     0.578947
9     0.642857
10    0.416667
11    0.636364
12    0.444444
13    0.500000
14    1.000000
15    1.000000
17    1.000000
Name: Outcome, dtype: float64

In [10]:
df.Glucose.unique()

array([148,  85, 183,  89, 137, 116,  78, 115, 197, 125, 110, 168, 139,
       189, 166, 100, 118, 107, 103, 126,  99, 196, 119, 143, 147,  97,
       145, 117, 109, 158,  88,  92, 122, 138, 102,  90, 111, 180, 133,
       106, 171, 159, 146,  71, 105, 101, 176, 150,  73, 187,  84,  44,
       141, 114,  95, 129,  79,   0,  62, 131, 112, 113,  74,  83, 136,
        80, 123,  81, 134, 142, 144,  93, 163, 151,  96, 155,  76, 160,
       124, 162, 132, 120, 173, 170, 128, 108, 154,  57, 156, 153, 188,
       152, 104,  87,  75, 179, 130, 194, 181, 135, 184, 140, 177, 164,
        91, 165,  86, 193, 191, 161, 167,  77, 182, 157, 178,  61,  98,
       127,  82,  72, 172,  94, 175, 195,  68, 186, 198, 121,  67, 174,
       199,  56, 169, 149,  65, 190])

In [12]:
df.groupby(['Glucose'])['Outcome'].mean()

Glucose
0      0.40
44     0.00
56     0.00
57     0.00
61     0.00
       ... 
195    1.00
196    1.00
197    0.75
198    1.00
199    1.00
Name: Outcome, Length: 136, dtype: float64

In [14]:
df.groupby(['BloodPressure'], as_index=False)['Outcome'].mean()

BloodPressure   Outcome
0               0  0.457143
1              24  0.000000
2              30  0.500000
3              38  0.000000
4              40  1.000000
5              44  0.000000
6              46  0.000000
7              48  0.200000
8              50  0.384615
9              52  0.272727
10             54  0.181818
11             55  0.000000
12             56  0.083333
13             58  0.095238
14             60  0.189189
15             61  0.000000
16             62  0.294118
17             64  0.302326
18             65  0.142857
19             66  0.366667
20             68  0.266667
21             70  0.403509
22             72  0.363636
23             74  0.326923
24             75  0.125000
25             76  0.461538
26             78  0.377778
27             80  0.325000
28             82  0.433333
29             84  0.521739
30             85  0.500000
31             86  0.428571
32             88  0.440000
33             90  0.500000
34             92  0.375000
35             94  0.500000
36             95  0.000000
37             96  0.250000
38             98  0.666667
39            100  0.333333
40            102  1.000000
41            104  1.000000
42            106  0.333333
43            108  0.500000
44            110  0.666667
45            114  1.000000
46            122  0.000000

In [16]:
df.groupby(['Insulin'], as_index=False)['Outcome'].mean()

Insulin   Outcome
0          0  0.368984
1         14  1.000000
2         15  0.000000
3         16  0.000000
4         18  0.000000
..       ...       ...
181      579  1.000000
182      600  1.000000
183      680  0.000000
184      744  0.000000
185      846  1.000000

[186 rows x 2 columns]

In [17]:
df.groupby(['Age'], as_index=False)['Outcome'].mean()

Age   Outcome
0    21  0.079365
1    22  0.152778
2    23  0.184211
3    24  0.173913
4    25  0.291667
5    26  0.242424
6    27  0.250000
7    28  0.285714
8    29  0.448276
9    30  0.285714
10   31  0.541667
11   32  0.562500
12   33  0.588235
13   34  0.285714
14   35  0.500000
15   36  0.625000
16   37  0.315789
17   38  0.625000
18   39  0.250000
19   40  0.461538
20   41  0.590909
21   42  0.388889
22   43  0.846154
23   44  0.625000
24   45  0.533333
25   46  0.538462
26   47  0.666667
27   48  0.200000
28   49  0.600000
29   50  0.625000
30   51  0.625000
31   52  0.875000
32   53  0.800000
33   54  0.666667
34   55  0.250000
35   56  0.666667
36   57  0.200000
37   58  0.428571
38   59  0.666667
39   60  0.400000
40   61  0.500000
41   62  0.500000
42   63  0.000000
43   64  0.000000
44   65  0.000000
45   66  0.500000
46   67  0.333333
47   68  0.000000
48   69  0.000000
49   70  1.000000
50   72  0.000000
51   81  0.000000

In [18]:
X = df.iloc[:, 0:-1]
Y = df.iloc[:, -1]

In [21]:
scaler = StandardScaler()
rescaledX = scaler.fit_transform(X)

new_df = pd.DataFrame(rescaledX, columns= X.columns)
new_df

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.639947  0.848324       0.149641       0.907270 -0.692891  0.204013   
1      -0.844885 -1.123396      -0.160546       0.530902 -0.692891 -0.684422   
2       1.233880  1.943724      -0.263941      -1.288212 -0.692891 -1.103255   
3      -0.844885 -0.998208      -0.160546       0.154533  0.123302 -0.494043   
4      -1.141852  0.504055      -1.504687       0.907270  0.765836  1.409746   
..           ...       ...            ...            ...       ...       ...   
763     1.827813 -0.622642       0.356432       1.722735  0.870031  0.115169   
764    -0.547919  0.034598       0.046245       0.405445 -0.692891  0.610154   
765     0.342981  0.003301       0.149641       0.154533  0.279594 -0.735190   
766    -0.844885  0.159787      -0.470732      -1.288212 -0.692891 -0.240205   
767    -0.844885 -0.873019       0.046245       0.656358 -0.692891 -0.202129   

     DiabetesPedigreeFunction       Age  
0                    0.468492  1.425995  
1                   -0.365061 -0.190672  
2                    0.604397 -0.105584  
3                   -0.920763 -1.041549  
4                    5.484909 -0.020496  
..                        ...       ...  
763                 -0.908682  2.532136  
764                 -0.398282 -0.531023  
765                 -0.685193 -0.275760  
766                 -0.371101  1.170732  
767                 -0.473785 -0.871374  

[768 rows x 8 columns]

In [22]:
new_df.describe()

Pregnancies       Glucose  BloodPressure  SkinThickness       Insulin  \
count  7.680000e+02  7.680000e+02   7.680000e+02   7.680000e+02  7.680000e+02   
mean  -6.476301e-17 -9.251859e-18   1.503427e-17   1.006140e-16 -3.006854e-17   
std    1.000652e+00  1.000652e+00   1.000652e+00   1.000652e+00  1.000652e+00   
min   -1.141852e+00 -3.783654e+00  -3.572597e+00  -1.288212e+00 -6.928906e-01   
25%   -8.448851e-01 -6.852363e-01  -3.673367e-01  -1.288212e+00 -6.928906e-01   
50%   -2.509521e-01 -1.218877e-01   1.496408e-01   1.545332e-01 -4.280622e-01   
75%    6.399473e-01  6.057709e-01   5.632228e-01   7.190857e-01  4.120079e-01   
max    3.906578e+00  2.444478e+00   2.734528e+00   4.921866e+00  6.652839e+00   

                BMI  DiabetesPedigreeFunction           Age  
count  7.680000e+02              7.680000e+02  7.680000e+02  
mean   2.590520e-16              2.451743e-16  1.931325e-16  
std    1.000652e+00              1.000652e+00  1.000652e+00  
min   -4.060474e+00             -1.189553e+00 -1.041549e+00  
25%   -5.955785e-01             -6.889685e-01 -7.862862e-01  
50%    9.419788e-04             -3.001282e-01 -3.608474e-01  
75%    5.847705e-01              4.662269e-01  6.602056e-01  
max    4.455807e+00              5.883565e+00  4.063716e+00

In [28]:
X_train, X_test, y_train, y_test = train_test_split(new_df, Y, test_size=0.3, random_state=42)

In [31]:
model = RandomForestClassifier(n_estimators=150)

params = {
    'criterion': ['gini', 'entropy'],
    'max_features': ['sqrt', 'log2', None],
    'class_weight': ['balanced', 'balanced_subsample']
}

grid_search = GridSearchCV(model, params, scoring='accuracy', cv=5)
grid_search.fit(X_train, y_train)


print(f'Best Params: {grid_search.best_params_}')
print(f'Best scores: {grid_search.best_score_}')
print(f'Best estimators: {grid_search.best_estimator_}')

Best Params: {'class_weight': 'balanced', 'criterion': 'entropy', 'max_features': 'sqrt'}
Best scores: 0.7802353755624784
Best estimators: RandomForestClassifier(class_weight='balanced', criterion='entropy',
                       n_estimators=150)


In [32]:
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))

[[122  29]
 [ 30  50]]


In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.81      0.81       151
           1       0.63      0.62      0.63        80

    accuracy                           0.74       231
   macro avg       0.72      0.72      0.72       231
weighted avg       0.74      0.74      0.74       231



In [35]:
import pickle
file = 'DiabetesPredModel.pkl'
with open(file, 'wb') as f:
    pickle.dump(model, f)